"""add field to specialization_score

Revision ID: 0cea396ae00c
Revises: bfdde6ae47eb
Create Date: 2025-09-04 02:25:53.216811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cea396ae00c'
down_revision: Union[str, Sequence[str], None] = 'bfdde6ae47eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialization_scores', sa.Column('seats', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('specialization_scores', 'seats', server_default=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialization_scores', 'seats')
    # ### end Alembic commands ###
