"""create exam_scores table

Revision ID: 1ca860b7be79
Revises: 539e7e827034
Create Date: 2025-09-02 23:54:26.391217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ca860b7be79'
down_revision: Union[str, Sequence[str], None] = '539e7e827034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject', postgresql.ENUM('MATH', 'RUSSIAN', 'PHYSICS', 'CHEMISTRY', 'BIOLOGY', 'HISTORY', 'COMPUTER_SCIENCE', 'FOREIGN_LANGUAGE', 'LITERATURE', name='subject_enum'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exam_scores_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exam_scores'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_scores')
    # ### end Alembic commands ###
