"""add interests to users tabel

Revision ID: bc9315e7c949
Revises: 1ca860b7be79
Create Date: 2025-09-03 00:15:07.623522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc9315e7c949'
down_revision: Union[str, Sequence[str], None] = '1ca860b7be79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('interest_tags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('users', sa.Column('full_interest_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_interest_text')
    op.drop_column('users', 'interest_tags')
    # ### end Alembic commands ###
