"""create specialization_scores table

Revision ID: bfdde6ae47eb
Revises: ede4104043f6
Create Date: 2025-09-03 11:41:44.296048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfdde6ae47eb'
down_revision: Union[str, Sequence[str], None] = 'ede4104043f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialization_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialization_id', sa.Integer(), nullable=False),
    sa.Column('minimal_score', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['specialization_id'], ['specializations.id'], name=op.f('fk_specialization_scores_specialization_id_specializations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_specialization_scores'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specialization_scores')
    # ### end Alembic commands ###
